"""add guest logic

Revision ID: c099666b3a66
Revises: ee813050f74a
Create Date: 2025-07-30 06:55:52.869308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c099666b3a66'
down_revision = 'ee813050f74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.drop_column('guests')

    # ### end Alembic commands ###
