"""add guest logic

Revision ID: e7d752f6d395
Revises: c099666b3a66
Create Date: 2025-07-30 08:07:34.066078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d752f6d395'
down_revision = 'c099666b3a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_key', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting', schema=None) as batch_op:
        batch_op.drop_column('meeting_key')

    # ### end Alembic commands ###
